name: testbuild
on: [push]
jobs:
    run-testbuild:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              with:
                path: f4se
            - uses: actions/checkout@v2
              with:
                path: common
                repository: ianpatt/common
            - run: cmake -B common/build -S common -DCMAKE_INSTALL_PREFIX=extern -DCMAKE_BUILD_TYPE=Release common
            - run: cmake --build common/build --target install
            - run: cmake -B f4se/build -S f4se -DCMAKE_INSTALL_PREFIX=extern -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON f4se
            - run: cmake --build f4se/build
